# Цвет фона - черный
background #000000

# Цвет текста - белый
foreground #ffffff

# Увеличенный начальный шрифт
font_size 20.0

# Укажите шрифт (замените на доступный на вашей системе)

font_family ComicShannsMono Nerd Font