#############################
###      ПЕРЕМЕННЫЕ       ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/


env = QT_QPA_PLATFORMTHEME,qt6ct    #  Использование qt6ct для настройки qt приложение
# env = XDG_CURRENT_DESKTOP,Hyprland  # Указывает текущий рабочий стол (Hyprland). Используется для корректной интеграции приложений.
# env = XDG_SESSION_TYPE,wayland      # Указывает тип сессии (Wayland). Необходимо для работы в Wayland. 
# env = XDG_SESSION_DESKTOP,Hyprland  # Указывает рабочий стол сессии (Hyprland). Используется для идентификации сессии. 
# env = QT_QPA_PLATFORM,wayland       # Указывает платформу для Qt-приложений (Wayland). Нужно для корректного отображения Qt-приложений. 
# env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1 # Отключает декорации окон для Qt-приложений. Использовать, если не нужны стандартные рамки окон.
# env = QT_SCALE_FACTOR,1             # Масштабирование для Qt-приложений. Установите значение, если нужно изменить масштабирование (например, 1.5 для HiDPI).
# env = GDK_SCALE,1                   # Масштабирование для GTK-приложений. Установите значение, если нужно изменить масштабирование (например, 2 для HiDPI).
# env = CLUTTER_BACKEND,wayland       # Указывает бэкенд для Clutter (Wayland). Используется для приложений на Clutter. 
# env = SDL_VIDEODRIVER,wayland       # Указывает видеодрайвер для SDL (Wayland). Используется для SDL-приложений. .
# env = ECORE_EVAS_ENGINE,wayland     # Указывает движок для Ecore-Evas (Wayland). Используется в EFL-приложениях. .
# env = ELM_ENGINE,wayland            # Указывает движок для Elementary (Wayland). Используется в EFL-приложениях. .
# env = ELM_ACCEL,opengl              # Указывает ускорение для Elementary (OpenGL). Используется для улучшения производительности. 
# env = WINIT_UNIX_BACKEND,wayland    # Указывает бэкенд для Winit (Wayland). Используется в Rust-приложениях. .


