# ####################################################
#                НАСТРЙОКИ ОБОЕВ                     #
# ####################################################


preload = ~/Изображения/1.jpg
wallpaper = , ~/Изображения/1.jpg