# See https://wiki.hyprland.org/Configuring/Keywords/




exec = gsettings set org.gnome.desktop.interface gtk-theme "Dracula"
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"

################
### CONFIGS ###
################



source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/win-work.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/look.conf
source = ~/.config/hypr/monitor.conf
source = ~/.config/hypr/enfi.conf
source = ~/.config/hypr/binds.conf
