# ####################################################
#                 НАСТРОЙКИ МОНИТОРА                 #
# ####################################################

# https://wiki.hyprland.org/Configuring/Monitors/




monitor=DP-1,2560x1440@75.0,0x0,1.0,bitdepth,10
