# ═══════════════════════════════════════════════════════════════════════════════
#                    WALKER LAUNCHER - NEON DARK THEME CONFIG
#                   Конфигурация интерфейса и размеров элементов
# ═══════════════════════════════════════════════════════════════════════════════

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │                           ПРИВЯЗКА ОКНА                                     │
# │  Определяет к каким краям экрана привязывается окно walker                  │
# └─────────────────────────────────────────────────────────────────────────────┘
[ui.anchors]
bottom = true # Привязка к нижнему краю экрана
left = true   # Привязка к левому краю экрана
right = true  # Привязка к правому краю экрана
top = true    # Привязка к верхнему краю экрана

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │                        ОСНОВНОЕ ОКНО WALKER                                 │
# │  Настройки выравнивания и заполнения главного окна                         │
# └─────────────────────────────────────────────────────────────────────────────┘
[ui.window]
h_align = "fill" # Горизонтальное заполнение экрана
v_align = "fill" # Вертикальное заполнение экрана

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │                      КОНТЕЙНЕР СОДЕРЖИМОГО                                  │
# │  Основной контейнер с содержимым walker (поиск, список, панель)            │
# └─────────────────────────────────────────────────────────────────────────────┘
[ui.window.box]
h_align = "center" # Центрирование по горизонтали
v_align = "center" # Центрирование по вертикали
width = 700        # Ширина контейнера в пикселях

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │                         НИЖНЯЯ ПАНЕЛЬ                                       │
# │  Панель с дополнительными кнопками внизу окна                              │
# └─────────────────────────────────────────────────────────────────────────────┘
[ui.window.box.bar]
orientation = "horizontal" # Горизонтальная ориентация панели
position = "end"           # Позиция в конце (внизу) контейнера

[ui.window.box.bar.entry]
h_align = "fill" # Заполнение по горизонтали
h_expand = true  # Расширение по горизонтали

[ui.window.box.bar.entry.icon]
h_align = "center" # Центрирование иконок
h_expand = true    # Расширение иконок
pixel_size = 24    # Размер иконок в пикселях
theme = ""         # Тема иконок (пустая = системная)

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │                        ОТСТУПЫ КОНТЕЙНЕРА                                   │
# │  Внешние отступы основного контейнера от краев экрана                      │
# └─────────────────────────────────────────────────────────────────────────────┘
[ui.window.box.margins]
top = 200 # Отступ сверху в пикселях

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │                      AI ОБЛАСТЬ ПРОКРУТКИ                                   │
# │  Настройки области для AI чата и взаимодействия                            │
# └─────────────────────────────────────────────────────────────────────────────┘
[ui.window.box.ai_scroll]
name = "aiScroll" # Имя элемента для CSS стилизации
h_align = "fill"  # Заполнение по горизонтали
v_align = "fill"  # Заполнение по вертикали
max_height = 300  # Максимальная высота в пикселях
min_width = 450   # Минимальная ширина в пикселях
height = 300      # Высота по умолчанию
width = 450       # Ширина по умолчанию

[ui.window.box.ai_scroll.margins]
top = 8 # Отступ сверху для AI области

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │                        AI СПИСОК СООБЩЕНИЙ                                  │
# │  Список сообщений в AI чате                                                │
# └─────────────────────────────────────────────────────────────────────────────┘
[ui.window.box.ai_scroll.list]
name = "aiList"          # Имя элемента для CSS стилизации
orientation = "vertical" # Вертикальная ориентация списка
width = 450              # Ширина списка
spacing = 10             # Расстояние между элементами

[ui.window.box.ai_scroll.list.item]
name = "aiItem"  # Имя элемента для CSS стилизации
h_align = "fill" # Заполнение по горизонтали
v_align = "fill" # Заполнение по вертикали
x_align = 0      # Выравнивание по X (0 = слева)
y_align = 0      # Выравнивание по Y (0 = сверху)
wrap = true      # Перенос текста

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │                      ОСНОВНОЙ СПИСОК РЕЗУЛЬТАТОВ                            │
# │  Список приложений и результатов поиска                                    │
# └─────────────────────────────────────────────────────────────────────────────┘
[ui.window.box.scroll.list]
max_height = 310 # Максимальная высота списка
max_width = 450  # Максимальная ширина списка
min_width = 450  # Минимальная ширина списка
width = 450      # Ширина списка по умолчанию

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │                      МЕТКИ АКТИВАЦИИ                                        │
# │  Настройки меток с горячими клавишами для быстрого запуска                 │
# └─────────────────────────────────────────────────────────────────────────────┘
[ui.window.box.scroll.list.item.activation_label]
h_align = "fill" # Заполнение по горизонтали
v_align = "fill" # Заполнение по вертикали
width = 20       # Ширина метки активации
x_align = 0.5    # Центрирование по X (0.5 = центр)
y_align = 0.5    # Центрирование по Y (0.5 = центр)

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │                         ИКОНКИ ЭЛЕМЕНТОВ                                    │
# │  Настройки иконок приложений в списке результатов                          │
# └─────────────────────────────────────────────────────────────────────────────┘
[ui.window.box.scroll.list.item.icon]
pixel_size = 26 # Размер иконок в пикселях
theme = ""      # Тема иконок (пустая = системная)

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │                       ОТСТУПЫ СПИСКА                                        │
# │  Внешние отступы списка результатов                                        │
# └─────────────────────────────────────────────────────────────────────────────┘
[ui.window.box.scroll.list.margins]
top = 8 # Отступ сверху от поля поиска

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │                        ПОЛЕ ПОИСКА                                          │
# │  Настройки элементов поля ввода поискового запроса                         │
# └─────────────────────────────────────────────────────────────────────────────┘

# Иконка поиска (лупа)
[ui.window.box.search.prompt]
name = "prompt"    # Имя элемента для CSS стилизации
icon = "edit-find" # Иконка поиска (лупа)
theme = ""         # Тема иконки (пустая = системная)
pixel_size = 18    # Размер иконки в пикселях
h_align = "center" # Центрирование по горизонтали
v_align = "center" # Центрирование по вертикали

# Кнопка очистки поля поиска
[ui.window.box.search.clear]
name = "clear"      # Имя элемента для CSS стилизации
icon = "edit-clear" # Иконка очистки (крестик)
theme = ""          # Тема иконки (пустая = системная)
pixel_size = 20     # Размер иконки в пикселях
h_align = "center"  # Центрирование по горизонтали
v_align = "center"  # Центрирование по вертикали

# Поле ввода текста
[ui.window.box.search.input]
h_align = "fill" # Заполнение по горизонтали
h_expand = true  # Расширение по горизонтали
icons = true     # Показывать иконки в поле ввода

# Индикатор загрузки
[ui.window.box.search.spinner]
hide = true # Скрыть индикатор загрузки
