# ~/.config/starship.toml

add_newline = true

format = """
$battery\
$os\
$hostname\
$directory\
$cmd_duration\
$container\
$docker_context\
$fill
$line_break\
$username\
$time\
$character\
"""

[character]
format = "$symbol "  
success_symbol = "[➜](bold #00bfff) "  
error_symbol = "[✗](bold #ff007f) "    
disabled = false  

[cmd_duration]
min_time = 100  
show_milliseconds = false  
format = "[⏳$duration](bold #00ced1) "  
disabled = false  

[container]
symbol = "🐳 "  
style = "bold #4682b4"  
format = "[$symbol$name]($style) "  
disabled = false  

[docker_context]
format = "via [$symbol$context](bold #5f9ea0) "  
symbol = "🐳 "  
only_with_files = true  
detect_extensions = []   
detect_files = ["docker-compose.yml", "Dockerfile"]  
detect_folders = []  
style = "bold #5f9ea0"  
disabled = false  

[directory]
truncation_length = 8       
truncate_to_repo = true      
format = "[$path]($style)[$read_only]($read_only_style) "  
style = "bold #FF0000"         
disabled = false            
read_only = "🔒"           
read_only_style = "bold #008b8b"  
truncation_symbol = "../"   
home_symbol = "🏠"          
use_os_path_sep = true       

[fill]
symbol = "━"
style = "bold #00ff7f"  
disabled = false  

[hostname]
ssh_only = false  
ssh_symbol = "🌐 "  
format = "[$ssh_symbol$hostname](bold #7fffd4) "  
disabled = false  

[line_break]
disabled = false  


[os]
format = "[$symbol]($style)"  
style = "bold #00bfff"  
disabled = false  
[os.symbols]      
Windows = " "
Macos = " "
Linux = "🙁"
Arch = " "
EndeavourOS = " "
CachyOS = " "
Unknown = " "

[time]
format = "[$time](bold #87ceeb) "  
use_12hr = false  
time_format = "%T"  
style = "bold #87ceeb"  
disabled = false  

[username]
style_root = "bold #00ffff"  
style_user = "bold #4682b4"  
format = "[💀$user]($style) "  
show_always = true  
disabled = false  
