# ================================================================
# Полный файл конфигурации для Satty с пояснениями
# Настройки, перед которыми стоит '#' - неактивны (закомментированы).
# Чтобы включить настройку, просто удалите '#' в начале строки.
# ================================================================

[general]
# --- Основное поведение ---

# Запускать Satty в полноэкранном режиме.
# fullscreen = true

# Выходить из программы сразу после сохранения или копирования.
# Если вы хотите сами решать, когда закрывать окно (например, по Esc), оставьте false.
early-exit = true

# --- Сохранение и Копирование ---

# Команда для копирования изображения в буфер обмена. 'wl-copy' - стандарт для Wayland.
copy-command = "wl-copy"

# Путь и формат имени файла для сохранения (Ctrl+S).
# %s - это UNIX-время (секунды), что гарантирует уникальность имени.
output-filename = "/home/smitee/Изображения/Скриншот-%S%3f.png"

# Также сохранять скриншот в файл после его копирования в буфер обмена (Ctrl+C).
# save-after-copy = false

# --- Горячие клавиши ---

# Действия при нажатии клавиши Enter. Можно указать несколько через запятую. Возможные значения: "save-to-clipboard", "save-to-file", "exit"

# Пример: actions-on-enter = ["save-to-clipboard", "exit"] (скопировать и выйти)
# actions-on-enter = ["save-to-clipboard"]

# Действия при нажатии клавиши Escape.
actions-on-escape = ["exit"]

# Действия при нажатии правой кнопки мыши.
# actions-on-right-click = []

# --- Внешний вид и инструменты ---

# Скругление углов у инструмента "Прямоугольник". Значение в пикселях. 0 - отключить.
 corner-roundness = 12

# Инструмент, который будет выбран по умолчанию при запуске.
# Возможные значения: "pointer", "crop", "line", "arrow", "rectangle", "ellipse", "text", "marker", "blur", "highlight", "brush"
# initial-tool = "arrow"

# Увеличение или уменьшение размера всех аннотаций (линий, текста и т.д.).
# 1.0 - стандартный размер. 2.0 - в два раза больше.
# annotation-size-factor = 1.0

# Скрывать панели инструментов по умолчанию при запуске.
#default-hide-toolbars = false

# Экспериментально: скрывать/показывать панели при потере/получении фокуса окном.
# focus-toggles-toolbars = false

# Режим для инструмента "Выделение" (Highlight/Marker) по умолчанию.
# Второй режим доступен по зажатию Ctrl.
# Возможные значения: "block" (прямоугольное выделение), "freehand" (рисование от руки).
# primary-highlighter = "block"

# Отключить системные уведомления (например, "Изображение скопировано").
disable-notifications = false

# Запрашивать у оконного менеджера окно без декораций (без заголовка и рамок).
no-window-decoration = true

# Экспериментально: сглаживание для инструмента "Кисть". 0 - отключено.
# Попробуйте значения от 5 до 10 для более плавных линий.
# brush-smooth-history-size = 0


# ================================================================
# Настройки шрифта для инструмента "Текст"
# ================================================================
[font]
# Семейство шрифта.
family = "Roboto"

# Стиль шрифта (зависит от установленных в системе).
# Например: "Regular", "Bold", "Italic", "Bold Italic".
# style = "Regular"


# ================================================================
# Настройки цветовой палитры
# ================================================================
[color-palette]
# Цвета, которые будут отображаться на панели инструментов для быстрого доступа.
# Укажите цвета в формате HEX.
# palette = [
#     "#ff5555", # Красный
#     "#50fa7b", # Зеленый
#     "#f1fa8c", # Желтый
#     "#8be9fd", # Голубой
#     "#bd93f9", # Фиолетовый
#     "#ff79c6", # Розовый
# ]

# Дополнительные цвета, которые будут доступны в полной палитре (в окне выбора цвета).
# Если оставить пустым, будут использоваться стандартные цвета GTK.
# custom = []